---
title: "Untitled"
author: "Jake Kramer"
date: "3/5/2020"
output: html_document 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
my_nchar <- function(x) {
  vapply(strsplit(x, ""), length, integer(1))    
}

my_strrep <- function(x, times) {
  suppressWarnings(mapply(function(a, b) {
    paste0(rep(a, b), collapse = "")
    }, a = x, b = times, USE.NAMES = FALSE))
  # vapply(times, function(n) {
  #   paste(rep(x, n), collapse = "")
  # },
  # character(1))  
}

`%is_in%` <- function(x, table) {
  # table <- as.character(table)
  # vapply(as.character(x), function(x) {
  #   isTRUE(any(grepl(paste0("\\b",x,"\\b"), table))) || is.na(x) && any(is.na(table))
  # }, logical(1), USE.NAMES = FALSE)
  x %in% table
}

get_match_lengths <- function(x, pattern) {
  nnx <- 0
  lengths <- integer(0)
  repeat {
    nx <- nchar(x)
    new_x <- sub(pattern, "", x)
    nnx <- nchar(new_x)
    if (nx == nnx) {
      break
    }
    lengths <- c(lengths, nx - nnx)
    x <- new_x
  }
  lengths
}
my_gregexpr <- function(pattern, text) {
  my_gregexpr_ <- function(pattern, text) {
    text_length <- nchar(text)
    keep_lengths <- nchar(unlist(strsplit(text, pattern)))
    if (identical(keep_lengths, text_length)) {
      out <- -1L
      pat_lengths <- -1L
    } else {
      pat_lengths <- get_match_lengths(text, pattern)
      idxs <- cumsum(keep_lengths + c(1L, head(pat_lengths, length(keep_lengths)  - 1)))[seq_along(pat_lengths)]
      out <- idxs[idxs + pat_lengths - 1L <= text_length]
    }
    # attributes(out) <- list(match.length = pat_lengths,
    #                         index.type = "chars",
    #                         useBytes = TRUE)
    list(out)
  }
  sapply(text, my_gregexpr_, pattern = pattern, USE.NAMES = FALSE)
}

pargsub <- function(text, patterns, replacements){
  if (length(patterns) != length(replacements)) {
    stop("patterns and replacements must be the same length.")
  }
    positions <- unlist(lapply(patterns, my_gregexpr, text), FALSE)
    positions <- lapply(positions, function(x) {
      if(identical(x, -1L)){
        integer(0)
      } else {
        x
      }
    })
    lengths <- vapply(positions, length, integer(1))
    keep <- unlist(strsplit(text, paste(patterns, collapse = "|")))
    substitutions <- lapply(seq_along(patterns), function(i) {
      rep(replacements[[i]], length.out = lengths[[i]])
    })
    to_insert <- unlist(substitutions)[order(unlist(positions))]
    padding <- rep("", length(keep) - length(to_insert))
    paste(keep, c(to_insert, padding), sep = "", collapse = "")  
}

keep_words <- function(words) {
  words[nchar(words) > 0]
}

is_special_ending <- function(ending) {
  is_es <- all(ending == c("e", "s"))
  is_ed <- all(ending == c("e", "d"))
  is_e_not_le <- ending[2] == "e" & ending[1] != "l"
  is_es | is_ed | is_e_not_le
}

rm_special_endings <- function(word_letters) {
  word_tail <- tail(word_letters, n = 2)
  if (is_special_ending(word_tail)) {
    if (word_tail[2] == "e") {
      word_letters[-length(word_letters)]
    } else {
      head(word_letters, n = -2)
    }
  } else {
    word_letters
  }
}

is_vowel <- function(letter) {
  letter %in% c("a", "e", "i", "o", "u", "y")
}

count_syllables <- function(word) {
  word_letters <- unlist(strsplit(word, split = ""))
  if (length(word_letters) <= 3) {
    1
  } else {
    word_letters <- rm_special_endings(word_letters)
    word_vowels <- is_vowel(word_letters)
    sum(word_vowels) - sum(diff(which(word_vowels)) == 1)
  }
}

reading_ease <- function(string) {
  if (length(string) > 1) {
    string <- paste(string, collapse = " ")
  }
  sentences <- unlist(strsplit(string, split = "[.!?::]"))
  sentences <- casefold(sentences)
  sentences <- gsub(pattern = "[[:punct:]]", replacement = "", sentences)
  sentences <- sentences[nchar(sentences) > 0]
  sentence_count <- length(sentences)
  string_words <- strsplit(sentences, split = " ")
  string_words <- unlist(lapply(string_words, keep_words))
  word_count <- length(string_words)
  word_syllables <- vapply(string_words, count_syllables, numeric(1))
  syllable_count <- sum(word_syllables)
  asl <- word_count / sentence_count
  asw <- syllable_count / word_count
  206.835 - (1.015 * asl) - (84.6 * asw)
}
```


